pub mod analyzer;
pub mod borrow_checker;
pub mod collector;
pub mod comptime;
pub mod ffi;
pub mod lifetime_checker;
pub mod module_registry;
pub mod module_resolver;
pub mod monomorphizer;
pub mod resolver;
pub mod specializer;
pub mod symbol_table;
pub mod trait_checker;
pub mod trait_resolver;
pub mod type_checker;
pub mod type_resolver;

pub use analyzer::SemanticAnalyzer;
pub use collector::SymbolCollector;
pub use comptime::{ComptimeEvaluator, ComptimeValue};
pub use ffi::FfiChecker;
pub use lifetime_checker::LifetimeChecker;
pub use module_registry::ModuleRegistry;
pub use module_resolver::ModuleResolver;
pub use monomorphizer::Monomorphizer;
pub use specializer::Specializer;
pub use trait_checker::TraitChecker;
pub use trait_resolver::TraitResolver;
pub use type_resolver::TypeResolver;
pub use symbol_table::{Symbol, SymbolKind, SymbolTable};
